### ISSUE TITLE
Empty CreateGraphicsPipeline function in 08_GraphicsPipeline

### ISSUE THREAD

**Issue by Vercidium** [dfkeenan/SilkVulkanTutorial#11]
The `CreateGraphicsPipeline()` function is empty in [Source/08_GraphicsPipeline/Program.cs](https://github.com/dfkeenan/SilkVulkanTutorial/blob/6df5ea68d73d63e0815cfbdd143102d859197eff/Source/08_GraphicsPipeline/Program.cs#L431), is that a typo?

**Comment by dfkeenan** [comment]
That is how it is in the source C++ code. Get's some implementation next chapter.

**Comment by Vercidium** [comment]
Perfect, just wanted to double check. Thanks!
