### ISSUE TITLE
Sample Framework

### ISSUE THREAD

**Issue by MrScautHD** [dfkeenan/SilkVulkanTutorial#5]
Hey!
What about a sample framework?

**Comment by dfkeenan** [comment]
Hi,

Thanks for the suggestion, however the purpose of this repository is to provide a 1 to 1 translation (or as close as possible) of the code in the original tutorials [repository](https://github.com/Overv/VulkanTutorial). So I will not be implementing such a framework.

Thanks,
dfkeenan
