### ISSUE TITLE
Request for Open-Source License Addition

### ISSUE THREAD

**Issue by ripwin** [dfkeenan/SilkVulkanTutorial#8]
Hello @dfkeenan,

I hope this message finds you well. I'm interested in contributing to your repository. However, I noticed it doesn't have an open-source license.

Could you please consider adding an open-source license to the repository? This would clarify the terms for contributions and usage.

Thank you!

Best regards,
Ripwin

**Comment by dfkeenan** [comment]
This is a derived work from https://github.com/Overv/VulkanTutorial. The code has the same license [CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/). I have updated the README to include this information.

I am not actively maintaining this repository. Other than occasionally updating NuGet packages references etc. It appears to no longer be up-to-date with the original tutorial.
